[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions" # Tell Netlify where our functions are

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Schedule the "cron" function to run daily at 8:00 UTC
[[functions]]
  name = "cron"
  schedule = "0 8 * * *"
